//
//  CharacterListModel.swift
//  Neapulse
//
//  Created by Vitor Kalil on 30/10/23.
//

import Foundation
import MapKit
import _MapKit_SwiftUI

struct CharacterList{
    var characters:[Character] = [
        Character(name: "Munaciello", history: "'Munaciello' is the monk who appears in the heart of the night and only to those in need. Without uttering a word, he beckons you to follow him, and only the bravest will be rewarded. It's said that many have suddenly found fortune through Munaciello's intervention. However, under no circumstances should one reveal the presence of the spirit, as doing so could bring bad luck. There are several hypotheses about the origin of this typical Neapolitan figure. The first, as reported by Matilde Serao in 'Neapolitan Legends', traces its origin back to 1445, during the reign of Alfonso V of Aragon. It was the result of the thwarted love between Caterinella Frezza, the daughter of a wealthy merchant, and a servant named Stefano Mariconda. Stefano was killed by Caterinella's family, and in her grief, she decided to take the veil. It was in the convent that she gave birth to a deformed child. She dressed the child as a monk, hoping for a miracle that never came. His figure, with a disproportionately large head and a frail body beneath the monk's robe, inspired horror and revulsion. The miracle never came, his health didn't improve, but he acquired supernatural powers, capable of bestowing good or evil upon others. Another theory links Munaciello to wells, deriving the name from those who managed them. This profession was often poorly compensated, which may have contributed to associating Munaciello with a vengeful figure.The third and final interpretation casts Munaciello in a very negative light, likening it to a demon.",caracteristic:"The mischievous spirit. The Munaciello, with its ability to manifest suddenly and influence the world around it through the feelings it evokes in others, shares a similarity with theater. Theater is also an ancient art of mystery and appearance, in which actors and performances can suddenly transform realitythrough the emotions they evoke in the audience. Your preference for theater and your willingness to spend all your time there show how fascinated you are by this art form. Naples, as one of the world's theater capitals, offers daily opportunities to immerse yourself in performances that evoke emotions and engage the audience.Similar to the Munaciello, you also pay close attention to how you are treated by others. Courtesy, kindness, and respect are essential to you, and if you don't receive these considerations, you are willing to take action to restore balance. Your priority is in mutual feelings and fair sharing, which reflects the Munaciello's nature. Strenghts: Ingenious, Generous, Mysterious. Dark Sides: Vindictive, Spiteful.", image: "monaciello",places:[
            PinPoint(name:"Teatro San Ferdinando",lat: 40.85737233527101, lon: 14.26403683014142),
            PinPoint(name:"Teatro Nuovo",lat: 40.85872560779331, lon: 14.284271199972954),
            PinPoint(name:"Sala Assoli",lat: 40.842434968204465, lon: 14.24802529208651),
            PinPoint(name:"Palazzo Fondi ",lat: 40.84102042130973, lon: 14.253103795774152),
            PinPoint(name:"Teatro Elicantropo",lat: 40.85292239073191, lon: 14.258207993930862),
            PinPoint(name:"Teatro Mercadante",lat: 40.8398575898241, lon: 14.254211182866996),
            PinPoint(name:"Teatro Bellini",lat: 40.851243964204706, lon: 14.250918923354067),
            PinPoint(name:"Teatro San Carlo",lat: 40.83759831050791, lon: 14.250195695773982),
            PinPoint(name:"Teatro Sannazaro",lat: 40.83593656107149, lon: 14.243605434371835),
    ]),
        
        Character(name: "Federico II", history: "Federico II of Swabia ascended to the throne as Emperor of the Holy Roman Empire in 1220, inheriting a vast realm that stretched from southern Germany to southern Italy. He is renowned for his eclecticism: he was a great patron of the arts and sciences, and one of the most enlightened rulers of his time. He is remembered as the 'Stupor Mundi' (the wonder of the world) for his extraordinary erudition and his fundamental role in the history of European culture. It was at his court that modern Italian literature and modern legislation were born. In Naples, he founded the world's first public and secular university: the University of Federico II, which remains a shining beacon of education throughout Europe to this day.",caracteristic:"The Bossy Majesty. Proud and regal in manners and appearance, you're free from rules. Like the emperor, you have astrong and dominant personality, and you definitely do not tolerate impositions. You're a free spirit capable to manifest both carnal and intellective side of your attitude, like Federico II. As every lover of beauty and culture, you're paradoxcally considered malleable: you're able to adapt at any of type of social event and people , without get contaminated fromm it, like every respectable leader. Lover of art in its entirety, in Naples, you can find some of the most important museums in the world, the works of great painters like Caravaggio, and the famous Veiled Christ. Strenghts: Art Lover, Wise, Regal. Dark sides: Bossy, Head in the cloud.", image: "federico",places:[
            PinPoint(name:"Museo Archeologico Nazionale",lat: 40.853736364915946, lon: 14.2505361097031),
            PinPoint(name:"Museo Madre",lat: 40.85526768020977, lon: 14.258940565096108),
            PinPoint(name:"PAN",lat: 40.837200188679226, lon: 14.23930404161263),
            PinPoint(name:"Museo Filangieri",lat: 40.849017784414364, lon: 14.260819246090565),
            PinPoint(name:"Palazzo Piacentini",lat: 42.95111577493638, lon: 13.87985771508079),
            PinPoint(name:"Museo di Capodimonte",lat: 40.86930459574876, lon: 14.251859639949663),
            PinPoint(name:"Pio Monte della Misericordia",lat: 40.85207392242962, lon: 14.260799063096165),
            PinPoint(name:"POMPEI RUINS",lat: 40.74834877170965, lon: 14.482303497023757),
            PinPoint(name:"OPLONTIS RUINS",lat: 40.757316282595774, lon: 14.45291653441303),
            PinPoint(name:"ERCOLANO RUINS",lat: 40.80894653278747, lon: 14.35489226827196),
    ]),
        
        Character(name: "Bella'Mbriana", history:"Bella 'Mbriana is the benevolent spirit of the house who watches over the inhabitants. If she enters the house in the form of a moth or a gecko, it's best not to chase her away. You could lose her protection and turn her hostile: it's even good to leave a chair free for her to sit in. There are numerous legends about her origin. According to a common myth, she would be the incarnation of a young woman abandoned at the altar, who, in despair, eventually lost her sanity and began to wander the streets of the city. What she loved most was to enter the houses of the Neapolitan inhabitants to spy on their daily lives. Her father, being a very wealthy man, decided to give money to those who offered shelter to the young woman, showing kindness to her. For this reason, it is said that the spirit leaves gifts here and there in the homes of honest people. Bella 'Mbriana is also a 1982 album by Pino Daniele, in which you can listen to the beautiful song written in her honor, which says: 'Bonasera Bella 'mbriana mia, ccà nisciuno te votta fore' (Good evening, my Bella 'Mbriana, here no one throws you out)... If you feel this benevolent spirit hovering over the house, if you sense a new harmony achieved in your family, try not to drive her away!", caracteristic:"The Kindhearted Spirit. Like “La bella mbriana”, a beautiful woman well dressed in white with the features of a children's fairy, you’re a pure kindhearted. Bella ‘Mbriana is the good spirit of the house. She chooses a place, a specific home in which to reside and places the chosen home under her care and protection. And you, you seem to be a reliable and generous friend. A point of reference for people who need support and listening. But you can also be vindictive if someone disturbs your peace! You don't like arguments and useless sneaky drama, but rather peace and reciprocal support and respect in your private relationships. As a kindhearted soul, you love music and could spend the entire day with your headphones. 'La Bella Mbriana' is a song by Pino Daniele, the most renowned Neapolitan singer-songwriter, which might help you understand who you are. Strenghts: Generous, Friendly, Musical. Dark sides: Talkative, Too generous, Vulnerable.", image: "bellambriana",places:[
            PinPoint(name:"Conservatorio di Musica di San Pietro a Maiella",lat: 40.849638820302246, lon: 14.25284363426067),
            PinPoint(name:"Palazzo Fondi",lat: 40.84100418799865, lon: 14.25323254179221),
            PinPoint(name:"Via san Sebastiano",lat: 40.848749754282835, lon: 14.25347400499391),
            PinPoint(name:"Munasterio ‘e santa Chiara",lat: 40.84721074176201, lon: 14.253377041792445),
            PinPoint(name:"Sorrento",lat: 40.627988209712015, lon: 14.372511607416293),
            PinPoint(name:"via Toledo",lat: 40.84265884250009, lon: 14.249140030729103),
            PinPoint(name:"Finestrella Marechiaro",lat: 40.7952984664736, lon: 14.192403694728162),
            PinPoint(name:"Santa Lucia",lat: 40.831800652819076, lon: 14.25082326878283),
            PinPoint(name:"Pino Daniele Alive",lat: 40.840889367213954, lon: 14.256229995104126),
            PinPoint(name:"Piazza Bellini",lat: 40.8499724492837, lon: 14.252992060916998),
            
    ]),
        
        Character(name: "Virgilio", history: "Virgilio was the greatest poet of the Latin tradition and one of the greatest in the history of world literature. He chose to move to Naples instead of living in Rome, the capital of the vast Roman Empire, because Naples offered him an environment steeped in Greek culture and philosophy, where he could write his works while being inspired by the generous and breathtaking nature. According to legend, as narrated by Matilde Serao, Virgil accomplished miracles and spells in Naples for the city's benefit. These powers included eliminating infestations of flies, getting rid of dangerous serpents, altering the direction of the winds, curing diseases, and much more. The most important act of the wizard Virgil was said to be the deposition of the sacred egg placed by Pulcinella beneath the Castel dell'Ovo, symbolizing the city's integrity until the end of time. In addition to composing literary works that will live on forever, the poet ensured the same fate for the city he loved so deeply. His remains rest in the Vergiliano Park in Piedigrotta, next to the final resting place of Italy's greatest poet, Giacomo Leopardi, who, like Virgil, chose to live in Naples.",caracteristic:"The Magician Poet. Introverted, Lover of privacy, literature, and nature. Virgil loved his solitude: on every occasion, he used to distance himself from Rome to stay in Naples, immersed in his poetic universe, in contact with the great intellectuals of the time. Lover of nature and peace, you might be considered an introvert, but you are simply very selective and capable of building an entire universe with your genius. Behind your quiet temperament, like Virgil, you are capable of great social skills. In fact, you are even famous for your renowned and wealthy frienship. In Naples, you can find a thriving literary city and discover readings capable of changing your life. Strenghts: Lyrical, Ingenious, Creative. Dark sides: Possessive, Tendency to isolate: Let your potential shine!", image: "virgilio",places:[
            PinPoint(name:"Port’Alba",lat:40.84960437226045, lon:14.250644397404585),
            PinPoint(name:"Libreria Colonnese",lat:40.84962066070808, lon:14.252189349781265),
            PinPoint(name:"Tomba di Virgilio",lat:40.82963505880539, lon:14.217180720253841),
            PinPoint(name:"Tomba di Leopardi",lat:40.83006125498717, lon:14.217566958308018),
            PinPoint(name:"La Feltrinelli a Chiaia" ,lat:40.83480618741223, lon:14.243071419658092),
            PinPoint(name:"La Feltrinelli a Garibaldi" ,lat:40.85329150657805, lon:14.272233418495947),
            PinPoint(name:"Palazzo Reale di Napoli",lat:40.83636950108079, lon:14.249681630569338),
            PinPoint(name:"Archivio Stato di Napoli",lat:40.848523576026274, lon:14.260027951600357),
            PinPoint(name:"BRAU Biblioteca di Ricerca di Area Umanistica",lat:40.85060316170955, lon:14.252645316532686),
            PinPoint(name:"Biblioteca del Dipartimento di Studi Umanistici di Napoli Federico II",lat:40.84495221354818, lon:14.259143469817507),
            PinPoint(name:"Gran Cafè Gambrinus",lat:40.83693246316111, lon:14.248993980434665),
            
        ]), 
       
        
        Character(name: "Partenope", history: "Partenope is the symbolic siren of Naples, and her ancient name, Παρθενόπη, means 'she who appears as a virgin'. It was the eponymous name of the first colony founded by the Cumaeans in the 8th century BC, located between Mount Vesuvius and the Phlegraean Fields, in front of the islet of Megaride: Partenope. Two centuries later, the Cumaeans refounded a 'New City', in Greek 'Nea Polis', at the site corresponding to today's historic center of Naples. Partenope was the mythical siren who, in despair, threw herself into the sea from a cliff. The reason was Ulysses. The siren's song was so enchanting and irresistible that no one could resist falling in love with her and rushing toward the depths, meeting their demise. The first human to resist her song was indeed Ulysses. During his journey back to Ithaca, he had himself tied to the ship's mainmast by his companions just to listen to the song and stay alive. The siren, rejected for the first time, took her own life. Her body reached the mouth of the Sebeto River, an ancient river that originated on Mount Vesuvius and flowed through Naples, which has since disappeared. In the past, she was worshipped as a deity, and it was believed that she would forever guard Partenope. Each year, the inhabitants of Partenope, and later Neapolis, would dedicate sacred rites and a solemn torchlight procession along the seaside in her honor.",caracteristic:"The Enchanting Beauty. Like Partenope, you do not need to be introduced: You’ve been gifted with a powerful sense of beauty and vanity. Everything for you, even the most simple thing, can radiate beauty in its purest form. This is one of your best capacities, which motivates your loved ones to reach the best version of themselves. But that’s not all! Mythology has shown that Sirens tempted Odysseus through the power of their sing, with the invitation 'to know more things'.  Your presence in people’s life often represent an invitation to that  so called 'omniscient' knowledge. You strongly believe that self awareness and self care is the most important act of beauty that can make our presence unique in the world; you always strive to be perfect in your grooming and dressing. In Naples, you will find the most exclusive boutiques, charming vintage shops, and top fashion brands. Strenghts: Always fashionable, cool, sexy. Dark sides: Slave of vanity and life pleasures.", image: "partenope",places:[
            PinPoint(name:"Via Toledo",lat: 40.84296726703087, lon: 14.249140030729103),
            PinPoint(name:"Via Mezzocannone",lat: 40.84676277463322, lon: 14.256763512957642),
            PinPoint(name:"Via Scarlatti",lat: 40.83689999453266, lon: 14.248811590242413),
            PinPoint(name:"Via dei Mille",lat: 40.83675678072083, lon: 14.238799066939174),
            
    ]),
        
        Character(name: "Pulcinella", history: "Pulcinella takes its name from 'Pullicinella' which is a Neapolitan term that means a chick, a little chicken. Its origin is indeed linked to rural culture. One of the most interesting anthropological theories about its origin traces it back to the spirit that transported the souls of the deceased to the afterlife. It is no coincidence that on the evening of a person's death, it was customary to eat chicken meat. Pulcinella, in all traditions, has a hooked nose, representing a beak. Pulcinella is a hermaphroditic figure, capable of laying an egg that, according to legend, resides beneath the Castel dell'Ovo, ensuring the city's integrity. A popular tradition from the 17th century traces the mask, known in Neapolitan as “Mezzasola”, to a peasant named Puccio d'Aniello, who joined a traveling troupe as a jester. However, the mask historically comes from the Latin tradition of Roman Atellane, where the character Maccus closely resembles the modern Pulcinella. It was with the spread of the Commedia dell'Arte that Pulcinella, one of the typical zanni or servant characters of the comedies, became famous worldwide. Portrayed and made great by actors like Fiorillo, Petito, De Filippo, drawn by Picasso, and celebrated by Stravinsky. It is the symbol of Neapolitan folklore, of contradictions and truths, of lies and honesty; it perfectly embodies the duality of the city: a city halfway between hunger and glory, between abundance and opulence, but at the same time poverty and thinness, halfway between wealth and poverty, between being a lord and being a peasant. The mask represents above all ingenuity, determination, the willingness to take risks, and courage. Pulcinella is known for its sweet idleness, complete relaxation, and its ability to get by. It never commits to anything other than finding something to eat and chew on: it is always eager for everything, especially food. Pulcinella is not stupid; it is a shrewd, intelligent, and astute person but completely listless, content to adapt to doing a bit of everything without ever truly committing to something. From this perspective, the mask represents in the collective imagination the classic Neapolitan citizen, one who does not give up in the face of difficulties and always finds a way to get by without losing their ironic smile. In other words, Pulcinella is Naples."
, caracteristic:"The Fool. Like Pulcinella, you are an enigmatic person and not easy to understand. Pulcinella is apparently opportunistic, but also ironic, sagacious, cheeky and talkative. Like him, you’re not afraid to face uncomfortable truths, and this makes you a man/woman of honor, but at the same time, not easy to have you around. You definitely have a low tolerance for arrogance and prevarications! Your charisma is contagious and you definitely love to be an inspiration for your dearest ones. You are also a great eater: what you like most is to sit at the table on Sundays with ragù or go out with friends to eat pizza. For you, food is like a religion. Strenghts: Ironic, Great Taster, Life of party. Dark sides: Confusionary, Stubborn.", image: "pulcinella",places:[
    PinPoint(name:"Pizzeria Totò e Gino Sorbillo ai Tribunali",lat:    40.85042370843084, lon:14.255266752476173),
PinPoint(name:"Antica Pizza Fritta zia Esterina Sorbillo a Toledo ",lat:    40.83754249418497, lon:14.248790771768313),
PinPoint(name:"Pizzeria Di Matteo ",lat:   40.85329639303906, lon:14.260720927625375),
PinPoint(name:"Pizzeria I Tribunali",lat:    40.851395515508194, lon:14.258019340591751),
PinPoint(name:"Ristorante Il Capriccio",lat:    40.830322113670796, lon:14.084009463090323),
PinPoint(name:"Pizzeria 50Kalò",lat:    40.851395515508194, lon:14.258019340591751),
PinPoint(name:"Ristorante ‘A Figlia d’o Marinaro",lat:    40.85943673071869, lon:14.26274405344467),
PinPoint(name:"Pizzeria Starita a Materie",lat:    40.856077352955296, lon:14.24630569451946),
PinPoint(name:"Pizzeria ‘A figlia d’o presidente ",lat:   40.85951787465821, lon:14.262186154033083),
PinPoint(name:"Pizzeria Masardona ",lat:   40.85201480573649, lon:14.273676963879064),
PinPoint(name:"Antica Pizzeria Da Michele",lat:    40.85135092044021, lon:14.27213197072589),
PinPoint(name:"Pasticceria F.lli Attanasio ",lat:    40.85335362897077, lon:14.269642612957922),
PinPoint(name:"Pasticceria Pintau",lat:    40.83941974413188, lon:14.248782778432084),
PinPoint(name:"Pasticceria Carraturo a Porta Capuana",lat:    40.85526886976596, lon:14.268109301306382),
PinPoint(name:"Gran Caffè Gambrinus ",lat:   40.83689999453266, lon:14.248811590242413),
]),
        
        Character(name: "Giovanna II", history: "Queen Giovanna reigned over Naples from 1414 until her death in 1435. Legends about her are historically based on the presence of 'favorites' at her court, illustrious and ambitious individuals with whom she liked to surround herself for the management of state affairs... and more. The queen was described as a dissolute woman, an insatiable and passionate lover who hosted men of all ages and social backgrounds in her bedchamber. After satisfying her desires with her lovers, she did not hesitate to get rid of them to protect her good reputation. Legends about this practice are numerous. It is even said that there was a trapdoor in her room, connected to the underground of Castel Nuovo (also known as Maschio Angioino), into which she would cast her lovers, dooming them to a grim fate among spikes and sharp blades. Similar legends are found in other places in Naples, and in Sorrento, there is a famous inlet where it is said that the queen would bathe with her lovers before throwing them off the surrounding cliff. These are the well-known 'baths of Queen Giovanna.' Only one man seems to have been truly loved by Giovanna II: Sergianni Caracciolo, the feared and hated Grand Seneschal of the Angevin kingdom and the third son of Francesco Caracciolo of the Del Sole branch. Sergianni Caracciolo had the most significant influence on Giovanna II and the fate of her reign. However, the more his thirst for power grew, the less the queen's love for him waned. She grew tired of indulging his demands and eventually conspired against him. Caracciolo was killed with twenty stab wounds by some assassins. Giovanna was as passionate as she was ruthless. Legend has it that many of her lovers were made to meet their end by her. Some even report hearing screams along the promenade on the Chiaia waterfront. These are said to be the voices of the lovers whom the mad Giovanna had grown tired of, those she had already seduced and no longer wished to entertain, and whom she killed without mercy.",caracteristic:"Queen of Luxury and Power Giovanna II d’Dangiò: one of the most discussed Queens, lover of power, but also of men. Like Giovanna you are passionate and charismatic. You love to surround yourself with life pleasures, which makes you an intense individual. People either love you or hate you. You love to be admired and recognized for your strong personality. Do you enjoy spending the evening having fun to excess, going to the nightclub, and maybe returning home in company. Strengths: Charismatic, Passionate, Sensual. Dark side: Attention seeking , Vanity, Arrogance.", image: "giovanna",places:[
            PinPoint(name:"Discoteca Paradiso",lat:    40.84174838630162, lon:14.11583308596644),
            PinPoint(name:"Alter Ego",lat:    40.854248100123336, lon:14.266677041516491),
            PinPoint(name:"Duel Club ",lat:   40.82811938387883, lon:14.15558178746603),
            PinPoint(name:"Club Partenopeo",lat:    40.80239702804564, lon:14.175604484120859),
            PinPoint(name:"Nessi",lat:    40.80085381023948, lon:14.174799457550641),
            PinPoint(name:"Shine Club",lat:    40.84517914599219, lon:14.211056111113741),
    ]),
        
        Character(name: "Pazzariello", history: "Pazzariello was a distinctive figure in Neapolitan popular culture, particularly prevalent between the late 18th and 19th centuries. This eccentric character played a unique role in the public street entertainment of Naples and has, over time, become an indelible icon in the hearts of Neapolitans. The term 'Pazzariello' derives from 'pazzo', meaning 'mad' or 'fool', and was used to describe a playful and amusing individual, often dressed flamboyantly, who performed on the streets with the aim of entertaining passersby. Their primary role was to spread cheer, ridicule seriousness, and bring smiles to anyone who crossed their path. The Pazzariello was known for their skills in harmless deception and the ability to make people laugh with their extravagant performances. Unlike modern street performers, Pazzariello did not need traditional musical instruments. Instead, they made a considerable racket using everyday objects like pots, ladles, and iron pipes. This cacophony of sounds, surprisingly, managed to spread joy among the people and bring a lively atmosphere of color and merriment to the often gloomy streets of the city of Naples. An important aspect of their work was the promotion of local shops and artisanal products. Many times, the Pazzariello would perform by holding bread and pasta to advertise the stores that produced such goods, performing a role similar to modern promoters outside restaurants and grocery stores. The Pazzariello was a well-received figure at local fairs and village festivals, where they worked to attract people and auction off items that would contribute to the funding of the festivities. Their presence and enthusiasm were able to enliven the celebrations and engage the audience uniquely. Although the Pazzariello is a figure from the past that has gradually faded with the advent of modernity, their memory and charm still live on in the hearts of Neapolitans. A memorable icon of this profession was portrayed by Totò in the film 'LOro di Napoli,' which brilliantly captured the vivacity and humor of this Neapolitan folklore figure.",caracteristic:"The picturesque bizzarre. Noisy and eccentric, you definitely do not like to go unnoticed! Pazzariello is playful and likes to emerge in every situation. You like to express your opinion even when you can sound inappropriate.Fearless and free from fear of judgment, Pazzariello has given voice to the people's will for centuries. And so do you! You like to be rawarded with attention and compliments. You easily get bored, so it is important for you to be surrounded by emotionally satisfying people who can handle your cheerful peppery temperament. You love to have an aperitif and spend crazy evenings with friends, in Naples, you'll find the perfect place for that. It's the city of Chaos and ecstasy! Strenghts: Life of party, Funny, Great drinking buddy. Dark sides: Attention seeker, Chaotic, Noisy.", image: "pazzariello",places:[
            PinPoint(name:"Spritz ai Quartieri Spagnoli",lat:    40.842189935688204, lon:14.247631961407778),
            PinPoint(name:"Drink a via Aniello Falcone",lat:    40.83971453863052, lon:14.22238114574503),
            PinPoint(name:"Ecstasy in Piazza Bellini",lat:    40.84999891382821, lon:14.252836195774591),
            PinPoint(name:"Baretti at Chiaia",lat:    40.8350081505035, lon:14.23968119610238),
            PinPoint(name:"Enoteche a Piazza del Gesù",lat:    40.8471946736282, lon:14.25189798471128),
                
                
                
                
            
    ]),
        
        Character(name: "San Gennaro", history: "San Gennaro is the revered patron saint of the city of Naples. He lived in the 3rd century A.D. during a period of intense Christian persecution in the Roman Empire.San Gennaro was originally from Benevento, where he later became a bishop. During his episcopate, Emperor Diocletian issued persecutory decrees against Christians. San Gennaro was arrested due to his faith and dedication to Christianity. Tradition tells us that San Gennaro endured various forms of torment and torture but refused to renounce his faith, remaining steadfast in his religious commitment. Among the tortures he endured was being cast into a blazing furnace by the decision of Timoteo di Nola. Miraculously, he emerged unscathed, and this event was said to bestow upon him the ability to control fire and even the Vesuvius itself. Neapolitans pray to San Gennaro to avert volcanic threats as a result. It's interesting to note that in every city in Naples, especially those near Mount Vesuvius, there is a statue of the saint or a statue of the Madonna, the only higher authority in terms of miracles. The saint's relics are preserved in the Naples Cathedral, among them, a vial containing his blood, which remains in solid form. This blood liquefies three times a year, demonstrating divine protection over Naples and its community: on the first Saturday in May, on September 19th (the city's patron saint feast day), and on December 16th. The Treasure of San Gennaro, comprised of valuable donations from his devoted followers and housed in the museum of the same name, is estimated to be worth over one billion euros in terms of its intrinsic value alone.",caracteristic:"The saint of Miracles. Like San Gennaro, you’re very respected and you often represent a strong point of referral for your dearest ones People comes to you for a wise advice and honest support. You represent that typical friend always ready to support without, however, being too condescending: you strongly believe in the power of words and promises. In your opinion, they must be used with care and attention. You’re definitely a man/woman of honor. That’s why most of people have faith in you. You love the sacred and the structures that humans have created to experience it. You are indeed a great explorer and discoverer of the reality around you, capable of wandering for hours in the heart of a city to understand its places and its people. Strenghts: Antropologist, Discoverer, Wise. Dark sides: Judgemental, Distracted.", image: "sanGennaro",places:[
            PinPoint(name:"Duomo di Napoli",lat:    40.85272134323437, lon:14.259835464940153),
            PinPoint(name:"Piazza del Gesù Nuovo ",lat:   40.846925681691545, lon:14.25188725587641),
            PinPoint(name:"Piazza Dante",lat:    40.8494212840916, lon:14.249932040537194),
            PinPoint(name:"Via San Gregorio Armeno",lat:    40.85024268207952, lon:14.25811030373847),
            PinPoint(name:"Certosa e Museo di San Martino",lat:    40.843840344764544, lon:14.240928171215664),
    ]),
        
        Character(name: "Posillipo", history: "Posillipo derives his name from the Greek Παυσίλυπον (Pausilypon) which literally means 'respite from danger' or 'which stops pain', a name linked to the panorama of the city coast and the gulf, a view which was enjoyed even two thousand years ago. Posillipo was a very nice boy, one of those always ready to help others, while Nisida was bad and enjoyed seducing boys, making them fall in love, and then rejecting them mercilessly. She also did the same thing with the young Posillipo who, destroyed by that rejection, decided to put an end to her existence by throwing herself off a cliff. However, fate could not let a young man with such a pure soul die from such wickedness, so it transformed him into one of the most beautiful promontories in Naples. The same treatment was not reserved for Nisida, who due to her meanness was transformed into an islet, located at the foot of the Posillipo promontory. Ironically, Posillipo and Nisida, due to the positions in which they were born, will be destined to look at each other forever, being one in front of the other and the isthmus that separates them will remain the emblem of that love that was never requited.",caracteristic:"You are passionate and sweet, like Posillipo. Your heart is rare and often not rewarded and appreciated enough. You are capable of giving love and seeing the good side even in the darkest people. Your soul is noble and gentle, and you are probably the one who has the greatest strength despite the countless difficulties that a pure heart like yours must face every day. Posillipo was transformed into one of the most beautiful promontories in Naples as a reward for his good soul that loved in vain. But you will surely be luckier! Your romantic soul finds peace in open places, always in contact with Nature. Naples, despite being highly urbanized, is surrounded by lush and generous nature. You will warm your heart cradled by breathtaking natural beauty. Strenghts: Romantic, Sweet, Undestanding. Dark sides: People pleasing, Suffering tendency.", image: "posillipo",places:[
            PinPoint(name:"Capodimonte",lat:   40.870053309634585, lon:14.250286894368152),
            PinPoint(name:"Villa Floridiana",lat:    40.84261153373333, lon:14.229257015389733),
            PinPoint(name:"Parco Nazionale del Vesuvio",lat:   40.82837852675291, lon:14.426678316644589),
            PinPoint(name:"Certosa di San Martino",lat:    40.843832228454836, lon:14.24132513810468),
                        
    ]),
        
        Character(name: "Sibilla Cumana", history: "Sibilla Cumana, also known as the Cumaean Sibyl, is a legendary and enigmatic figure in ancient Roman and Greek mythology. She was a priestess dedicated to Apollo, the god of prophecy and oracles. The name 'Cumana' is derived from her association with Cumae, an ancient city in Italy where her renowned cave, known as the 'Antro della Sibilla', is located. According to the myth, Apollo fell in love with the beautiful Sibilla and offered to grant her any wish in exchange for her eternal devotion. She made a seemingly simple request, grasping a handful of sand and asking for as many years of life as there were grains in her hand. Apollo granted her wish, but the Sibilla had not specified eternal youth. As a result, she aged rapidly and eventually disappeared, leaving only her eternal voice, which continued to deliver prophecies and oracles to Apollo's faithful. Sibilla Cumana's legacy endures as a symbol of prophecy, divination, and the mystical connection between the human and divine realms, making her a captivating figure in the rich tapestry of ancient mythology and history.",caracteristic:"The Mysterious Sensitive. Like Sibilla Cumana, you definitely have a great intuition. It doesn't take much for you to understand the person in front of you. For this reason, people can often fear you and feel under exam in front of you: they know it’s very difficult to lie to you. You are capable of great persuasion. You can also read the future and plan your life for the best. It's very difficult to access at your emotional and private side, But your defensive mechanism hide a garden of loyalty and love. Sibilla Cumana preserved her the state of virginity in the name of love, and this translates to you in the noble capability to make sacrifices for your life passions and loved ones. You also have a passion for danger and mystery. In Naples, you can experience your witchcraft, discovering many mystical and secret places. Strenghts: Prophetic, Mysterious, Intuitive. Dark sides:  Diffident, Stubborn.", image: "sibillacumana",places:[
            PinPoint(name:"Tomba di Dracula",lat:    40.84383255832718, lon:14.252838696362744),
            PinPoint(name:"Cristo Velato",lat:    40.84946325889704, lon:14.254881356464919),
            PinPoint(name:"Napoli Sotterranea",lat:     40.83741866467329, lon:14.246012591927075),
            PinPoint(name:"Antro della Sibilla",lat:    40.84784780876693, lon:14.054015545480278),
            PinPoint(name:"Pompei Villa dei Misteri",lat:    40.753717800381395, lon:14.477966455283827),
            PinPoint(name:"Cimitero delle Fontanelle",lat:   40.8587990398775, lon:14.239481099308296),
                
                
                
                
    ]),
        
        Character(name: "Colapesce", history: "Colapesce is a young boy from the Porto district who had a deep love for the sea. He was so enamored with the sea that he would never return home due to his long dives. His mother's concern for his prolonged absences soon turned into desperation, ultimately leading to a curse placed upon him. Cola, his real name, began to take on a progressively monstrous and fish-like appearance. First came the scales and then the gills. He would move along the seabed 'aboard' enormous fish, hiding within their stomachs, only to cut their bellies open upon reaching his destination. His story is widely renowned and is narrated in the Neapolitan version by Benedetto Croce, who links the myth to the figure of the sons of Neptune, magical divers who could hold their breath in apnea to find treasures and unravel the secrets of the sea. Just like Colapesce, a poor boy who preferred the mysteries of the sea to the life of men. In every true Neapolitan, firmly connected to their beloved Mediterranean Sea, there is a bit of Colapesce.",caracteristic:"Son of the sea. The sea is your home, like Colapesce, you often immerse yourself in the depths of the sea as the best remedy for your well-being. You are a curious and adventurous person, always in search of treasures and riches. You are the ideal friend to have new experiences with and go on vacations. In Naples, with its beaches, along its coast and islands, you will find some of the most enchanting places on Earth, perfect for someone like you with a soul like Capri. You feel comfortable in dynamic environments, and it is essential for you to be surrounded by open-minded personalities, always ready to push their limits. You would never tolerate stereotypes and sterile communication. You are like the sea, vibrant and free, boundless and vast. Strengths: Free, Adventurous, Enterprising. Dark sides: Imprudent, Unpredictable, Contradictory.", image: "colapesce",places:[
            PinPoint(name:"Spiaggia di Marechiaro",lat:    40.795105525498386, lon:14.191019139369212),
            PinPoint(name:"Baia delle Rocce Verdi ",lat:   40.79763193773961, lon:14.199584656961477),
            PinPoint(name:"Spiaggia libera di Seiano",lat:    40.66117343647469, lon:14.419877281760295),
            PinPoint(name:"Capri",lat:    40.56337744108201, lon:14.206166439858883),
            PinPoint(name:"Ischia",lat:    40.72443163877118,lon: 13.95830732163132),
            PinPoint(name:"Procida ",lat:   40.76658721227363, lon:14.022173301348946),
            PinPoint(name:"Spiaggia dell’Oncino ",lat:   40.754114354110406, lon:14.433333097594904),
     
    ])
    ]
}


