//
//  CharacterListModel.swift
//  Neapulse
//
//  Created by Vitor Kalil on 30/10/23.
//

import Foundation

struct CharacterList{
    var characters:[Character] = [
        Character(name: "Munaciello", history: "",caracteristic:"The mischievous spirit. The Munaciello, with its ability to manifest suddenly and influence the world around it through the feelings it evokes in others, shares a similarity with theater. Theater is also an ancient art of mystery and appearance, in which actors and performances can suddenly transform realitythrough the emotions they evoke in the audience. Your preference for theater and your willingness to spend all your time there show how fascinated you are by this art form. Naples, as one of the world's theater capitals, offers daily opportunities to immerse yourself in performances that evoke emotions and engage the audience.Similar to the Munaciello, you also pay close attention to how you are treated by others. Courtesy, kindness, and respect are essential to you, and if you don't receive these considerations, you are willing to take action to restore balance. Your priority is in mutual feelings and fair sharing, which reflects the Munaciello's nature. Strenghts: Ingenious, Generous, Mysterious. Dark Sides: Vindictive, Spiteful.", image: "monaciello"),
        
        Character(name: "Federico II", history: "",caracteristic:"The Bossy Majesty. Proud and regal in manners and appearance, you're free from rules. Like the emperor, you have astrong and dominant personality, and you definitely do not tolerate impositions. You're a free spirit capable to manifest both carnal and intellective side of your attitude, like Federico II. As every lover of beauty and culture, you're paradoxcally considered malleable: you're able to adapt at any of type of social event and people , without get contaminated fromm it, like every respectable leader. Lover of art in its entirety, in Naples, you can find some of the most important museums in the world, the works of great painters like Caravaggio, and the famous Veiled Christ. Strenghts: Art Lover, Wise, Regal. Dark sides: Bossy, Head in the cloud.", image: "federico"),
        
        Character(name: "Bella'Mbriana", history:"", caracteristic:"The Kindhearted Spirit. Like “La bella mbriana”, a beautiful woman well dressed in white with the features of a children's fairy, you’re a pure kindhearted. Bella ‘Mbriana is the good spirit of the house. She chooses a place, a specific home in which to reside and places the chosen home under her care and protection. And you, you seem to be a reliable and generous friend. A point of reference for people who need support and listening. But you can also be vindictive if someone disturbs your peace! You don't like arguments and useless sneaky drama, but rather peace and reciprocal support and respect in your private relationships. As a kindhearted soul, you love music and could spend the entire day with your headphones. 'La Bella Mbriana' is a song by Pino Daniele, the most renowned Neapolitan singer-songwriter, which might help you understand who you are. Strenghts: Generous, Friendly, Musical. Dark sides: Talkative, Too generous, Vulnerable.", image: "bellambriana"),
        
        Character(name: "Virgilio", history: "",caracteristic:"The Magician Poet. Introverted, Lover of privacy, literature, and nature. Virgil loved his solitude: on every occasion, he used to distance himself from Rome to stay in Naples, immersed in his poetic universe, in contact with the great intellectuals of the time. Lover of nature and peace, you might be considered an introvert, but you are simply very selective and capable of building an entire universe with your genius. Behind your quiet temperament, like Virgil, you are capable of great social skills. In fact, you are even famous for your renowned and wealthy frienship. In Naples, you can find a thriving literary city and discover readings capable of changing your life. Strenghts: Lyrical, Ingenious, Creative. Dark sides: Possessive, Tendency to isolate: Let your potential shine!", image: "virgilio"),
        
        Character(name: "Partenope", history: "",caracteristic:"The Enchanting Beauty. Like Partenope, you do not need to be introduced: You’ve been gifted with a powerful sense of beauty and vanity. Everything for you, even the most simple thing, can radiate beauty in its purest form. This is one of your best capacities, which motivates your loved ones to reach the best version of themselves. But that’s not all! Mythology has shown that Sirens tempted Odysseus through the power of their sing, with the invitation 'to know more things'.  Your presence in people’s life often represent an invitation to that  so called 'omniscient' knowledge. You strongly believe that self awareness and self care is the most important act of beauty that can make our presence unique in the world; you always strive to be perfect in your grooming and dressing. In Naples, you will find the most exclusive boutiques, charming vintage shops, and top fashion brands. Strenghts: Always fashionable, cool, sexy. Dark sides: Slave of vanity and life pleasures.", image: "partenope"),
        
        Character(name: "Pulcinella", history: "", caracteristic:"The Fool. Like Pulcinella, you are an enigmatic person and not easy to understand. Pulcinella is apparently opportunistic, but also ironic, sagacious, cheeky and talkative. Like him, you’re not afraid to face uncomfortable truths, and this makes you a man/woman of honor, but at the same time, not easy to have you around. You definitely have a low tolerance for arrogance and prevarications! Your charisma is contagious and you definitely love to be an inspiration for your dearest ones. You are also a great eater: what you like most is to sit at the table on Sundays with ragù or go out with friends to eat pizza. For you, food is like a religion. Strenghts: Ironic, Great Taster, Life of party. Dark sides: Confusionary, Stubborn.", image: "pulcinella"),
        
        Character(name: "Giovanna II", history: "",caracteristic:"Queen of Luxury and Power Giovanna II d’Dangiò: one of the most discussed Queens, lover of power, but also of men. Like Giovanna you are passionate and charismatic. You love to surround yourself with life pleasures, which makes you an intense individual. People either love you or hate you. You love to be admired and recognized for your strong personality. Do you enjoy spending the evening having fun to excess, going to the nightclub, and maybe returning home in company. Strengths: Charismatic, Passionate, Sensual. Dark side: Attention seeking , Vanity, Arrogance.", image: "giovanna"),
        
        Character(name: "Pazzariello", history: "",caracteristic:"The picturesque bizzarre. Noisy and eccentric, you definitely do not like to go unnoticed! Pazzariello is playful and likes to emerge in every situation. You like to express your opinion even when you can sound inappropriate.Fearless and free from fear of judgment, Pazzariello has given voice to the people's will for centuries. And so do you! You like to be rawarded with attention and compliments. You easily get bored, so it is important for you to be surrounded by emotionally satisfying people who can handle your cheerful peppery temperament. You love to have an aperitif and spend crazy evenings with friends, in Naples, you'll find the perfect place for that. It's the city of Chaos and ecstasy! Strenghts: Life of party, Funny, Great drinking buddy. Dark sides: Attention seeker, Chaotic, Noisy.", image: "pazzariello"),
        
        Character(name: "San Gennaro", history: "",caracteristic:"The saint of Miracles. Like San Gennaro, you’re very respected and you often represent a strong point of referral for your dearest ones People comes to you for a wise advice and honest support. You represent that typical friend always ready to support without, however, being too condescending: you strongly believe in the power of words and promises. In your opinion, they must be used with care and attention. You’re definitely a man/woman of honor. That’s why most of people have faith in you. You love the sacred and the structures that humans have created to experience it. You are indeed a great explorer and discoverer of the reality around you, capable of wandering for hours in the heart of a city to understand its places and its people. Strenghts: Antropologist, Discoverer, Wise. Dark sides: Judgemental, Distracted.", image: "sanGennaro"),
        
        Character(name: "Posillipo", history: "",caracteristic:"You are passionate and sweet, like Posillipo. Your heart is rare and often not rewarded and appreciated enough. You are capable of giving love and seeing the good side even in the darkest people. Your soul is noble and gentle, and you are probably the one who has the greatest strength despite the countless difficulties that a pure heart like yours must face every day. Posillipo was transformed into one of the most beautiful promontories in Naples as a reward for his good soul that loved in vain. But you will surely be luckier! Your romantic soul finds peace in open places, always in contact with Nature. Naples, despite being highly urbanized, is surrounded by lush and generous nature. You will warm your heart cradled by breathtaking natural beauty. Strenghts: Romantic, Sweet, Undestanding. Dark sides: People pleasing, Suffering tendency.", image: "posillipo"),
        
        Character(name: "Sibilla Cumana", history: "",caracteristic:"The Mysterious Sensitive. Like Sibilla Cumana, you definitely have a great intuition. It doesn't take much for you to understand the person in front of you. For this reason, people can often fear you and feel under exam in front of you: they know it’s very difficult to lie to you. You are capable of great persuasion. You can also read the future and plan your life for the best. It's very difficult to access at your emotional and private side, But your defensive mechanism hide a garden of loyalty and love. Sibilla Cumana preserved her the state of virginity in the name of love, and this translates to you in the noble capability to make sacrifices for your life passions and loved ones. You also have a passion for danger and mystery. In Naples, you can experience your witchcraft, discovering many mystical and secret places. Strenghts: Prophetic, Mysterious, Intuitive. Dark sides:  Diffident, Stubborn.", image: "sibillacumana"),
        
        Character(name: "Colapesce", history: "",caracteristic:"Son of the sea. The sea is your home, like Colapesce, you often immerse yourself in the depths of the sea as the best remedy for your well-being. You are a curious and adventurous person, always in search of treasures and riches. You are the ideal friend to have new experiences with and go on vacations. In Naples, with its beaches, along its coast and islands, you will find some of the most enchanting places on Earth, perfect for someone like you with a soul like Capri. You feel comfortable in dynamic environments, and it is essential for you to be surrounded by open-minded personalities, always ready to push their limits. You would never tolerate stereotypes and sterile communication. You are like the sea, vibrant and free, boundless and vast. Strengths: Free, Adventurous, Enterprising. Dark sides: Imprudent, Unpredictable, Contradictory.", image: "colapesce")
    ]
}
